### PR TITLE
Added a custom object detector project to the repository 

### LINKED ISSUE #7: Custom Object Detection
This is a problem where we'll be using tensorflow and deep learning to detect an object of our choice in images. We'll also be using augmentation and other techniques to increase our dataset. In this project, I have used two types of Keys as our subject, and I have collected images on my own, You can use the images in the repo or you can also use freely available datasets. You will also need [LabelImg](https://github.com/heartexlabs/labelImg) to annotate the images.

### PR DESCRIPTION
**Pull request by Adw8**
As the title says, I added a complete custom object detection project, including the dataset, for any ML enthusiasts trying to learn this field of Deep Learning. I have also created a README file, that includes a description of the project, the steps involved in executing the project, any additional information that the viewer may need, as well as the results that the user can expect if everything goes well. It also has links to other resources and pictures for better understanding.

Fixes #7

### CODE REVIEW

**Comment by Adw8** [comment]
@kunalagra As discussed, I have uploaded the project and created a PR, Kindly merge it, or let me know if there are any changes.

**Comment by Adw8** [comment]
Hi @kunalagra, as discussed, I have uploaded a project and created a PR, kindly merge it or let me know if there are any changes, Thanks!

**Comment by kunalagra** [comment]
Hey @Adw8.
Some suggestions:
1. Remove the SS from Libraries and just list them down as a list in your Readme.md
2. Rename the file Custom_Object_Detector (1).ipynb to Custom_Object_Detector.ipynb
3. Add your Name & Github repo at End of Readme.md file
4. remove Train & Test folder, rather create a separate public repo on your github and link it in the Readme.md. This will allow this repo to be of less bloat.
5. Rename the Folder to House & TVS Key Detection

**Comment by Adw8** [comment]
Hello @kunalagra,
Changes made:
1. removed ss and added libraries in a list in readme
2. renamed the ipynb file and folder name
3. removed train and test folder and added a link to it on my personal github acc
4. added my name and github at the end of the readme

If any more changes, do let me know, Thanks!

**Comment by kunalagra** [comment]
Looks lot better. Thank You for the contribution.

It's merged.

Just a small feedback: Try to write better commit messages, you can look it up online on how to do so. Further, don't have too many commits with same fiel edit. Try to do the bulk load of edit in a file in single commit as to avoid Commit History being spammed.

**Pull request merged**
